import type { GetStaticProps, NextPage } from "next";
import axios from "axios";
import Head from "next/head";
import useSWR from 'swr';
import View, { CoinData } from "../components/view";
import styles from "../styles/Home.module.css";
import { CoinsData } from "../components/view";
import { QueryParams } from "../components/view";
import { useEffect, useState } from "react";


// const url = "https://jsonplaceholder.typicode.com/posts";

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View />
    </div> //swr hook
  );
};

export default Home;
