import type { NextPage } from "next";
import { GetServerSideProps } from "next";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import View, { CoinData } from "../components/view";
import styles from "../styles/Home.module.css";
import { CoinsData } from "../components/view";


const Home: NextPage<CoinsData> = ({ coinsData }) => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View coinsData={coinsData}/>
    </div> //swr hook
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  let response = await axios.get(
    `https://api.coingecko.com/api/v3/coins/markets`,
    {
      params: {
        vs_currency: "usd",
        order: "market_cap_desc",
        per_page: 10,
        page: 1,
        sparkline: false,
      },
    }
  );
  console.log("fecthed");
  return {
    props: {
      coinsData: response.data,
    },
  };
};

export default Home;
